### ISSUE TITLE
Build did not open on Big Sur / mac

### ISSUE THREAD

**Issue by AngledStream** [DannyVanIets/wolfskin#15]
Ok So one of my beta readers was going to go through itbut it wont open for them on their mac
" Something about my mac being incompatible with the drive? I'm really sorry DX" she says
"I have the Mac OS Big Sur Version 11.5.2 MacBook Pro 2019"

**Comment by robotortoise** [comment]
We have tested on other OS X devices and the build appears to be 64-bit. Big Sur does not work with 32-bit devices, and this beta tester does not have time to test it with us so we are closing this issue for now until we can get more evidence/screenshots, or one of our devs can screen share with the beta tester to determine what is wrong.

Possible PEBKAC error.
