### ISSUE TITLE
Script Change: "A large clock tower looms" to "A bell tower looms"

### ISSUE THREAD

**Issue by AngledStream** [DannyVanIets/wolfskin#9]
4. The town is bustling despite not being very large. A large clock tower looms....
to
The town is bustling despite not being very large. A bell tower dawns....

Three changes here. Replace clocktower with bell tower (for consistency sake and OST). Replace loom with dawn, I noticed that we used loom too many times in the script. Remove the word large, used that word again.

**Comment by tamafry** [comment]
Cannot change to 'bell' due to a continuity error in the original script. Other changes are reflected and made.
